db Client (little)
ZeLebo/Timetable pull request #30
Opened 2022-11-22 18:30 UTC by vovademar

2022-11-22 18:43 UTC, ZeLebo requested changes
Ну короче, в целом всё нормально, просто надо эту логику разбить на класс с методами и использовать уже имеющие entities (возможно, там сразу как-то можно заставить их складываться в бд (через аннотации) чекни этот момент и напиши)

В целом, основная задача выполнена, молодец, но надо немного поправить

2022-11-22 18:43 UTC, ZeLebo commented on src/main/kotlin/nsu/repository/DBClient.kt
> +fun main() {
Сделай тут отдельный класс, типа DBClient
Внутри должна лежать сама сущность db (ты её получаешь из Connect)

2022-11-22 18:43 UTC, ZeLebo commented on src/main/kotlin/nsu/repository/DBClient.kt
> +    val jdbcUrl = "jdbc:postgresql://localhost:5432/timetable_db"
Это вынеси в логику метода Connect (он void)

2022-11-22 18:43 UTC, ZeLebo commented on src/main/kotlin/nsu/repository/DBClient.kt
> +    data class Students(val id: Int, val first_name: String, val last_name: String, val group_id: Int)
У тебя уже есть класс Student, надо использовать его (entities.people.Student)

2022-11-22 18:43 UTC, ZeLebo commented on src/main/kotlin/nsu/repository/DBClient.kt
> +    }
Это логика метода GetAllStudents, надо вынести отдельно)

2022-11-22 18:43 UTC, ZeLebo commented on src/main/kotlin/nsu/repository/DBClient.kt
> +
Тут комментарии аналогичные предыдущим, надо использовать Group из entity и вынести логику получения группы в отдельный метод

2022-11-22 18:43 UTC, ZeLebo commented on src/main/kotlin/nsu/repository/DBClient.kt
> +}
Короче, сам класс будет выглядеть как-то так
class A {
init {
try {
this.Connect()
} catch Exception {
throw Exception("Cannot connect to database")
}
}

fun Connect() {
val jurl = "somethin"
var connection = DriverManager.getConnection()
// test the connection to database
try {
// тут надо посмотреть, в каком формате он выдает ошибку и обработать
connection.Ping
} catch CannotConnectDatabase {
throw Exception("cannot connect to database")
} else {
this.db = connection
}
}


fun GetAllStudent() : List<Student> {}
fun GetAllGroups() :List<Group> {}
}


Что еще добавить? Надо добавить метод добавления student'а (или, если я не прав, и надо класть его где-то выше, написать об это)

Возможно, придется изменить сущность некоторых entity - меняй (пока ничего важного нет, только в AddController дергается student.name можешь его переименовать через shift+F6, там ничего важного нет

2022-11-26 16:55 UTC, ZeLebo commented
Так, не меняй пока сами entity, они там поменяются в другом месте

2022-11-26 16:56 UTC, vovademar commented
понял👌

2022-11-28 08:47 UTC, ZeLebo commented
появится метод studentToGroup(naming student, number group) {
// find group id
// find student id
// put them into StudentToGroup table (one to many relation)
}

2022-11-28 12:08 UTC, ZeLebo approved these changes
Пойдет

2022-11-28 12:08 UTC, merged